# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
  jobs:
    # Setuptools_scm needs an unshallow clone to get the correct version information
    post_checkout:
      - git fetch --unshallow
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements-rtd.txt
      # LSMTool itself needs to be installed to generate the documentation.
    - method: pip
      path: .

