# This dockerfile is used throughout steps of the CI/CD pipeline
# It contains dependencies to run tests
FROM python:3.13

RUN python -m pip install --upgrade pip
RUN python -m pip install --upgrade tox twine
